### ISSUE TITLE
PA Review: User Authentication 

### ISSUE THREAD

**Issue by omarnyte** [omarnyte/bandstand#1]
- [x] Backend: DB, model, controller, views 
- [x] Redux Loop: ajax, actions, reducer 
- [x] Presentational Components 
- [x] Styling 
- [x] Smooth, bug-free navigation 
- [x] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
This looks great!! Only have a few comments, find them below:

## Functionality

- [ ] Have the BandCamp logo be a link to `/`
- [ ] `https://bandstandfullstack.herokuapp.com/#/ornvoierbovib` should redirect me to `/`

## Style

- [ ] If all errors are displayed on signup, the bottom of the form breaks
